---
- name: "Preconfig"
  hosts: all
  tasks:
    - name: "Install Docker"
      block:
        - name: "Adding the universe"
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_relese }} universe"
            state: present

        - name: "Install sopport package"
          apt:
            name:
              - apt-transport-https
              - ca-certificate
              - curl
              - gnupg
              - lsb-release
            update_cache: yes
            cache_valid_time: 3600

        - name: "Adding Docker key"
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: "Adding stable repository Docker"
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_relese }} stable
            state: present
            update_cache: yes
            filename: docker

        - name: "Install Docker-ce"
          apt:
            name: docker-ce 
            state: present
            update_cache: yes

        - name: "Check status docker-ce service and restarting"
          service:
            name: docker
            state: restarted
            enabled: yes